=== paulnetedu/genarview/GenArView-FW/src/genarview-dsl-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.genarview.pmmc.pro/genarview-dsl-1.0" xmlns:tns="http://www.genarview.pmmc.pro/genarview-dsl-1.0" elementFormDefault="qualified">

    <include schemaLocation=""></include>
    <include schemaLocation=""></include>
    <element name="dsl">
    	<complexType>
    		<sequence minOccurs="1" maxOccurs="1">
    			<element name="lookFor" type="tns:TypeLookFor"
    				minOccurs="0" maxOccurs="1">
    			</element>
    			<element name="hintHards" type="tns:TypeHintHards"
    				minOccurs="0" maxOccurs="1">
    			</element>
    			<element name="hintSofts" type="tns:TypeHintSofts"
    				minOccurs="0" maxOccurs="1">
    			</element>
    			<element name="queryCompTyper" type="tns:TypeQueryCompTyper"
    				minOccurs="0" maxOccurs="unbounded">
    			</element>
    			<element name="graph" type="tns:TypeGraph" minOccurs="0" maxOccurs="1"></element>
    			<element name="measures" type="tns:TypeMeasures"
    				minOccurs="0" maxOccurs="1">
    			</element>
    		</sequence>
    	</complexType>
    </element>

    <complexType name="TypeHintExp">
    	<complexContent>
    		<extension base="tns:TypeCompTyper">
    			<sequence minOccurs="0" maxOccurs="1">
		    		<choice minOccurs="1" maxOccurs="1">
		    			<element name="hintAnd" type="tns:TypeHintAnd"></element>
		    			<element name="hintOr" type="tns:TypeHintOr"></element>
		    		</choice>
		    	</sequence>
    			<attribute name="name" type="string"></attribute>
    		</extension>
    	</complexContent>
    	
    </complexType>

    <complexType name="TypeHintPlain">
    	<complexContent>
    		<extension base="tns:TypeHintMember">
   			<sequence>
   				<element name="class" type="string"
   					minOccurs="1">
   				</element>
   				<element name="value" type="tns:TypeValue"
   					minOccurs="0" maxOccurs="unbounded">
   				</element>
   			</sequence>
    		</extension>
    	</complexContent> 
    </complexType>


    <complexType name="TypeHintHards">
    	<sequence>
    		<element name="hintSource" type="tns:TypeHintSource"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    		<element name="hintDescriptor" type="tns:TypeHintDescriptor"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>
    
    

    



    <complexType name="TypeHintAnd">
    	<complexContent>
    		<extension base="tns:TypeHintSet"></extension>
    	</complexContent>
    </complexType>
    
    <complexType name="TypeHintOr">
    	<complexContent>
    		<extension base="tns:TypeHintSet"></extension>
    	</complexContent>
    </complexType>
    
    <complexType name="TypeHintSet">
    	<complexContent>
    		<extension base="tns:TypeHintMember">
		<choice minOccurs="1" maxOccurs="unbounded">
			<element name="hintAnd" type="tns:TypeHintAnd">
			</element>
			<element name="hintOr" type="tns:TypeHintOr">
			</element>
			<element name="hint" type="tns:TypeHintPlain"></element>
		</choice>
    		</extension>
    	</complexContent>
    </complexType>





    <complexType name="TypeFunction">
   		<sequence>
   			<group ref="tns:GroupImpl" minOccurs="1" maxOccurs="1"/>
    		<element name="implements" type="tns:TypeLinkImplements"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    		<element name="extends" type="tns:TypeLinkExtends"
    			minOccurs="0" maxOccurs="1">
    		</element>
    		<element name="refs" type="tns:TypeLinkReferences"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    		<element name="label" type="string" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="TypeArgs">
    	<sequence>
    		<element name="arg" type="string" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>


    <complexType name="TypeLinker"></complexType>

    <complexType name="TypeLinkImplements">
    	<complexContent>
    		<extension base="tns:TypeLinker"></extension>
    	</complexContent>
    </complexType>
    
    <complexType name="TypeLinkExtends">
    	<complexContent>
    		<extension base="tns:TypeLinker"></extension>
    	</complexContent>
    </complexType>

    <complexType name="TypeValue">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="key" type="string" use="required"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>

	<complexType name="TypeDefaulter">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="default" type="string" use="required"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>
    <complexType name="TypeHintMember"></complexType>

    <complexType name="TypeLinkReferences">
    	<complexContent>
    		<extension base="tns:TypeLinker"></extension>
    	</complexContent>
    </complexType>

    <complexType name="TypeHintCustom">
    	<complexContent>
    		<extension base="tns:TypeCompTyper">
		    	<sequence>
		    		<group ref="tns:GroupImpl"/>
		    	</sequence>
	    	</extension>
	    </complexContent>
    </complexType>

    <complexType name="TypeHintNaming">
    	<complexContent>
    		<extension base="tns:TypeCompTyper">
	    	<sequence>
	    		<element name="pack" type="string" minOccurs="1" maxOccurs="1"></element>
	    		<element name="word" type="tns:TypeWord" minOccurs="1" maxOccurs="unbounded"></element>
	    	</sequence>
	    	</extension>
	    </complexContent>
    </complexType>
    
    <complexType name="TypeHintSofts">
    	<sequence minOccurs="0" maxOccurs="1">
    		<element name="hintNaming" type="tns:TypeHintNaming"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    		<element name="hintCustom" type="tns:TypeHintCustom" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="TypeWord">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="position" type="int"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>

    <complexType name="TypeCompTyper">
    	<sequence>
    		<element name="componentType" type="string" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>


    <complexType name="TypeQueryCompTyper">
    	<complexContent>
    		<extension base="tns:TypeCompTyper">
                <sequence>
                	<group ref="tns:GroupImpl" />
                	<element name="query" type="string" minOccurs="0"
                		maxOccurs="1">
                	</element>
                	<element name="fnn" type="tns:TypeFunction" minOccurs="0"
                		maxOccurs="unbounded">
                	</element>
                </sequence>
                <attribute name="name" type="string"></attribute>
            </extension>
    	</complexContent>
    </complexType>

    <group name="GroupImpl">
    	<sequence>
    		<element name="class" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="arg" type="string" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="args" type="tns:TypeArgs" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    </group>
    <group name="GroupQuery">
    	<sequence>
    		<element name="query" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="param" type="tns:TypeValue" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    </group>




	<!-- Useful for record and identify Annotation full names when the code has import aaa.* -->  
    <complexType name="TypeMetadata">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="level" use="required">
    				<simpleType>
    					<restriction base="string">
    						<enumeration value="Class"></enumeration>
    						<enumeration value="Method"></enumeration>
    						<enumeration value="Field"></enumeration>
    						<enumeration value="Param"></enumeration>
    					</restriction>
    				</simpleType>
    			</attribute>
    		</extension>
    	</simpleContent>
    </complexType> 


    <complexType name="TypeMethod">
    	<simpleContent>
    		<extension base="string"></extension>
    	</simpleContent>
    </complexType>

    <complexType name="TypeLookFor">
    	<sequence>
    		<element name="metadata" type="tns:TypeMetadata"
    			minOccurs="0" maxOccurs="unbounded">
    		</element>
    		<element name="methodCall" type="tns:TypeMethod" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="TypeHintSource">
    	<complexContent>
    		<extension base="tns:TypeHintExp">
    			<sequence>
    				<element name="fnn" type="tns:TypeFunction" minOccurs="0" maxOccurs="1"></element>
    			</sequence>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="TypeHintDescriptor">
    	<complexContent>
    		<extension base="tns:TypeHintExp">
    			<sequence>
	    			<element name="fpp" type="tns:TypeFunction" minOccurs="0" maxOccurs="1"></element>
					<element name="fpn" type="tns:TypeFunction" minOccurs="1" maxOccurs="1"></element>
					<element name="fnn" type="tns:TypeFunction" minOccurs="0" maxOccurs="1"></element>
	    		</sequence>
    		</extension>
    	</complexContent>
    </complexType>
    
    <complexType name="TypeMeasure">
    	<sequence minOccurs="1" maxOccurs="1">
    		
    		<element name="measureData" type="tns:TypeMeasureData" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="measureMap" type="tns:TypeMeasureMap" minOccurs="1" maxOccurs="unbounded"></element>
    		<element name="measureMapComposite" type="tns:TypeMeasureMapComposite" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    
    <complexType name="TypeMeasureData">
    	<sequence minOccurs="1" maxOccurs="1">
    		<!-- gets results from a query or from an implementation -->
    		<choice>
    			<group ref="tns:GroupQuery" />
    			<group ref="tns:GroupImpl" />
    		</choice>
    		<!-- adds results from other measuredata -->
    		<element name="measureData" type="tns:TypeMeasureData" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="idField" type="string" minOccurs="1"></element>
    		<!-- join results -->
    		<element name="join" type="tns:TypeJoin" minOccurs="0"
    			maxOccurs="1"></element>
    		<!-- transform results by a map function -->
    		<element name="fmap" type="tns:TypeFunction" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>
	<complexType name="TypeMeasures">
    	<sequence>
    		<element name="query" type="tns:TypeQuery" minOccurs="0" maxOccurs="unbounded"></element>
    		<element name="measure" type="tns:TypeMeasure" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
	</complexType>

    <complexType name="TypeQuery">
    	<sequence>
    		<element name="query" type="string" minOccurs="1"></element>
    		<element name="value" type="string" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>


    <complexType name="TypeMeasureMap">
    	<complexContent>
    		<extension base="tns:TypeFunction">
    			<sequence>
    				<element name="key" type="string" minOccurs="1"
    					maxOccurs="1">
    				</element>
    				<element name="formula" type="tns:TypeFormula" minOccurs="0" maxOccurs="1"></element>
    				<element name="reducer" type="tns:TypeMeasureReduce"
    					minOccurs="0" maxOccurs="unbounded">
    				</element>
    			</sequence>
    			<attribute name="name" type="string" use="required"></attribute>
    			
    		</extension>
    	</complexContent>
    </complexType>
    
    <complexType name="TypeMeasureReduce">
    	<complexContent>
    		<extension base="tns:TypeFunction">
    			<!-- key is the map key to be shown in results -->
    			<attribute name="key" type="string" use="required"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="TypeMeasureMapComposite">
    	<sequence>
    		<element name="key" type="string" minOccurs="1"
		    			maxOccurs="1"></element>
    		<element name="formula" type="string" minOccurs="1"></element>
    		<element name="measureMapName" type="string"
    			minOccurs="2" maxOccurs="unbounded">
    		</element>
    		<element name="reducer" type="tns:TypeMeasureReduce"
    			minOccurs="0" maxOccurs="1">
    		</element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="TypeJoin">
    	<sequence>
    		<element name="fromField" type="string" minOccurs="1" maxOccurs="1"></element>
    		<element name="measureData" type="tns:TypeMeasureData" minOccurs="1"
    			maxOccurs="1"></element>
    		<element name="forField" type="tns:TypeDefaulter" minOccurs="1" maxOccurs="unbounded"></element>
    		<element name="join" type="tns:TypeJoin" minOccurs="0"
    			maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="TypeFormula">
    	<sequence>
    		<element name="var" type="string" minOccurs="1"
    			maxOccurs="unbounded">
    		</element>
    		<element name="condition" type="tns:TypeFormulaCondition" minOccurs="0" maxOccurs="unbounded"></element>
    		<element name="exp" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="TypeFormulaCondition">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="type" use="required">
    				<simpleType>
    					<restriction base="string">
    						<enumeration value="equalTo"></enumeration>
    						<enumeration value="lesserThan"></enumeration>
    						<enumeration value="greaterThan"></enumeration>
    						<enumeration value="notEqualTo"></enumeration>
    						<enumeration value="greaterEqualTo"></enumeration>
    						<enumeration value="lesserEqualTo"></enumeration>
    					</restriction>
    				</simpleType>
    			</attribute>
    			<attribute name="exp" type="string" use="required"></attribute>
    			<attribute name="expVal" type="string" use="required"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>

    <complexType name="TypeGraph">
    	<sequence>
    		<element name="glabel" type="tns:TypeGLabel" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="gupdate" type="string" minOccurs="0" maxOccurs="unbounded"></element>
    		<element name="grun" type="string" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>
    
    <complexType name="TypeGLabel">
    	<sequence>
    		<element name="field" type="tns:TypeGLabelField" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="for" type="string" use="required"></attribute>
    </complexType>

    <complexType name="TypeGLabelField">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="preffix" type="string"
    				use="optional">
    			</attribute>
    			<attribute name="suffix" type="string" use="optional"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>
</schema>

=== paulnetedu/genarview/GenArView-FW/src/genarview-dsl-1.0-copia.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:dsl xmlns:tns="http://www.genarview.pmmc.pro/genarview-dsl-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.genarview.pmmc.pro/genarview-dsl-1.0 genarview-dsl-1.0.xsd ">
  <tns:lookFor>
  <tns:metadata level="Class">javax.inject.Named</tns:metadata>
  <tns:metadata level="Class">javax.servlet.annotation.WebServlet</tns:metadata>
  <tns:metadata level="Class">javax.jws.WebService</tns:metadata>
  <tns:metadata level="Class">javax.xml.ws.WebServiceRef</tns:metadata>
  <tns:metadata level="Class">javax.ejb.MessageDriven</tns:metadata>
  
  <tns:metadata level="Class">javax.persistence.Entity</tns:metadata>   
  <tns:metadata level="Class">javax.persistence.Table</tns:metadata>
  <tns:metadata level="Class">javax.persistence.JoinTable</tns:metadata>
  <tns:metadata level="Class">javax.persistence.AuditJoinTable</tns:metadata>
  <tns:metadata level="Class">javax.ws.rs.Path</tns:metadata>
  <tns:metadata level="Class">javax.ws.rs.GET</tns:metadata>
  <tns:metadata level="Class">javax.ws.rs.POST</tns:metadata>
  <tns:metadata level="Class">javax.ws.rs.PUT</tns:metadata>
  <tns:metadata level="Class">javax.ws.rs.QueryParam</tns:metadata>
  <tns:metadata level="Class">javax.ws.rs.Consumes</tns:metadata>
  <tns:metadata level="Class">javax.ws.rs.Produces</tns:metadata>
  <tns:metadata level="Class">javax.ws.rs.OPTIONS</tns:metadata>
  
  <tns:methodCall>createQuery</tns:methodCall>
  </tns:lookFor>
  <tns:hintHards>
  	<!-- ANDROID -->
    <tns:hintSource name="Activity">
    	<tns:componentType>Activity</tns:componentType>
    	<tns:hintAnd>
		        <tns:hint>
		        	<tns:class>pro.pmmc.genarview.functional.predicate.node.PWithUnitExtendsImported</tns:class>
		        	<tns:value key="baseClassFullName">android.app.Activity</tns:value>
		        </tns:hint>
	    </tns:hintAnd>
    </tns:hintSource>
    <tns:hintSource name="Fragment">
    	<tns:componentType>Fragment</tns:componentType>
    	<tns:hintAnd>
		        <tns:hint>
		        	<tns:class>pro.pmmc.genarview.functional.predicate.node.PWithUnitExtendsImported</tns:class>
		        	<tns:value key="baseClassFullName">android.app.Fragment</tns:value>
		        </tns:hint>
	    </tns:hintAnd>
    </tns:hintSource>
    <tns:hintSource name="Service">
    	<tns:componentType>Service</tns:componentType>
    	<tns:hintOr>
		        <tns:hint>
		        	<tns:class>pro.pmmc.genarview.functional.predicate.node.PWithUnitExtendsImported</tns:class>
		        	<tns:value key="baseClassFullName">android.app.Service</tns:value>
		        </tns:hint>
		        <tns:hint>
		        	<tns:class>pro.pmmc.genarview.functional.predicate.node.PWithUnitExtendsImported</tns:class>
		        	<tns:value key="baseClassFullName">android.app.IntentService</tns:value>
		        </tns:hint>
	    </tns:hintOr>
    </tns:hintSource>
    <tns:hintSource name="BroadcastReceiver">
    	<tns:componentType>BroadcastReceiver</tns:componentType>
    	<tns:hintAnd>
		        <tns:hint>
		        	<tns:class>pro.pmmc.genarview.functional.predicate.node.PWithUnitExtendsImported</tns:class>
		        	<tns:value key="baseClassFullName">android.content.BroadcastReceiver</tns:value>
		        </tns:hint>
	    </tns:hintAnd>
    </tns:hintSource>
    <tns:hintSource name="ContentProvider">
    	<tns:componentType>ContentProvider</tns:componentType>
    	<tns:hintAnd>
		        <tns:hint>
		        	<tns:class>pro.pmmc.genarview.functional.predicate.node.PWithUnitExtendsImported</tns:class>
		        	<tns:value key="baseClassFullName">android.content.ContentProvider</tns:value>
		        </tns:hint>
	    </tns:hintAnd>
    </tns:hintSource> 
  	<!-- JEE -->
    <!-- tns:hintSource name="Stateless">
    	<tns:componentType>EJB</tns:componentType>
    	<tns:componentType>SessionEJB</tns:componentType>
    	<tns:componentType>Stateless</tns:componentType>
  		<tns:hintOr>
		        <tns:hint>
		        	<tns:class>pro.pmmc.genarview.functional.predicate.node.PWithAnnotation</tns:class>
		        	<tns:value key="annotationLevel">TYPE</tns:value>
	      			<tns:value key="annotationName">Stateless</tns:value>
		        </tns:hint>
	    </tns:hintOr>
    </tns:hintSource>
    <tns:hintSource name="Stateful">
    	<tns:componentType>EJB</tns:componentType>
    	<tns:componentType>SessionEJB</tns:componentType>
    	<tns:componentType>Stateful</tns:componentType>
  		<tns:hintOr>
		        <tns:hint>
		        	<tns:class>pro.pmmc.genarview.functional.predicate.node.PWithAnnotation</tns:class>
		        	<tns:value key="annotationLevel">TYPE</tns:value>
	      			<tns:value key="annotationName">Stateful</tns:value>
		        </tns:hint>
        </tns:hintOr>
    </tns:hintSource>
    <tns:hintSource name="Singleton">
    	<tns:componentType>EJB</tns:componentType>
    	<tns:componentType>SessionEJB</tns:componentType>
    	<tns:componentType>Singleton</tns:componentType>
  		<tns:hintOr>
		        <tns:hint>
		        	<tns:class>pro.pmmc.genarview.functional.predicate.node.PWithAnnotation</tns:class>
		        	<tns:value key="annotationLevel">TYPE</tns:value>
	      			<tns:value key="annotationName">Singleton</tns:value>
		        </tns:hint>
	    </tns:hintOr>
    </tns:hintSource-->
    
  </tns:hintHards> 
  <!-- tns:queryCompTyper name="Facade">
    	<tns:componentType>Facade</tns:componentType>
    	<tns:class>pro.pmmc.genarview.query.GenericQueryCompTyper</tns:class>
    	<tns:args>
    		<tns:arg>b</tns:arg>
    	</tns:args>
    	<tns:query>MATCH (b:SessionEJB)-[:REFERENCE]->(e1:Type)-[:T_HAS_ANNOTATION]->(a1:Annotation), (b:SessionEJB)-[:REFERENCE]->(e2:Type)-[:T_HAS_ANNOTATION]->(a2:Annotation) WHERE not(e1 = e2) AND (a1.name="Local" OR a1.name="Remote") AND (a2.name="Local" OR a2.name="Remote")  
		</tns:query>
    </tns:queryCompTyper>
    <tns:queryCompTyper name="Dependency injection" >
    	<tns:componentType>DI</tns:componentType>
    	<tns:class>pro.pmmc.genarview.query.GenericQueryCompTyper</tns:class>
    	<tns:args>
    		<tns:arg>b</tns:arg>
    	</tns:args>
    	<tns:query>MATCH (b:Type)-[:T_HAS_ANNOTATION]->(a:Annotation:Field) WHERE a.fullName="javax.inject.Inject"   
		</tns:query>
    </tns:queryCompTyper>
    <tns:queryCompTyper name="Factory method" >
    	<tns:componentType>FactoryMethod</tns:componentType>
    	<tns:class>pro.pmmc.genarview.query.GenericQueryCompTyper</tns:class>
    	<tns:args>
    		<tns:arg>b</tns:arg>
    	</tns:args>
    	<tns:query>MATCH (b:Type)-[:T_HAS_ANNOTATION]->(a:Annotation:Method) WHERE a.fullName="javax.enterprise.inject.Produces"   
		</tns:query>
    </tns:queryCompTyper>
    <tns:queryCompTyper name="Decorator" >
    	<tns:componentType>Decorator</tns:componentType>
    	<tns:class>pro.pmmc.genarview.query.GenericQueryCompTyper</tns:class>
    	<tns:args>
    		<tns:arg>b</tns:arg>
    	</tns:args>
    	<tns:query>MATCH (b:Type)-[:T_HAS_ANNOTATION]->(a:Annotation:Class) WHERE a.fullName="javax.decorator.Decorator"   
		</tns:query>
    </tns:queryCompTyper>
    <tns:queryCompTyper name="Interceptor" >
    	<tns:componentType>Interceptor</tns:componentType>
    	<tns:class>pro.pmmc.genarview.query.GenericQueryCompTyper</tns:class>
    	<tns:args>
    		<tns:arg>b</tns:arg>
    	</tns:args>
    	<tns:query>MATCH (b:Type)-[:T_HAS_ANNOTATION]->(a:Annotation:Class) WHERE a.fullName="javax.interceptor.Interceptor"   
		</tns:query>
    </tns:queryCompTyper>
    <tns:queryCompTyper name="Asynchronous" >
    	<tns:componentType>Asynchronous</tns:componentType>
    	<tns:class>pro.pmmc.genarview.query.GenericQueryCompTyper</tns:class>
    	<tns:args>
    		<tns:arg>b</tns:arg>
    	</tns:args>
    	<tns:query>MATCH (b:Type)-[:T_HAS_ANNOTATION]->(a:Annotation:Method) WHERE a.fullName="javax.ejb.Asynchronous"   
		</tns:query>
    </tns:queryCompTyper>  
    <tns:queryCompTyper name="TimerService" >
    	<tns:componentType>TimerService</tns:componentType>
    	<tns:class>pro.pmmc.genarview.query.GenericQueryCompTyper</tns:class>
    	<tns:args>
    		<tns:arg>b</tns:arg>
    	</tns:args>
    	<tns:query>MATCH (b:Type)-[:T_HAS_ANNOTATION]->(a:Annotation:Method) WHERE a.fullName="javax.ejb.Schedule" OR a.fullName="javax.ejb.Timeout"  
		</tns:query>
    </tns:queryCompTyper>
    <tns:queryCompTyper name="Observer" >
    	<tns:componentType>Observer</tns:componentType>
    	<tns:class>pro.pmmc.genarview.query.GenericQueryCompTyper</tns:class>
    	<tns:args>
    		<tns:arg>b</tns:arg>
    	</tns:args>
    	<tns:query>MATCH (b:Type)-[:T_HAS_ANNOTATION]->(a:Annotation:Param) WHERE a.fullName="javax.enterprise.event.Observes"  
		</tns:query>
    </tns:queryCompTyper>
    <tns:queryCompTyper name="RESTFulService" >
    	<tns:componentType>RESTFulService</tns:componentType>
    	<tns:class>pro.pmmc.genarview.query.GenericQueryCompTyper</tns:class>
    	<tns:args>
    		<tns:arg>b</tns:arg>
    	</tns:args>
    	<tns:query>MATCH (b:Type)-[:T_HAS_ANNOTATION]->(a:Annotation:Class) WHERE a.fullName="javax.ws.rs.Path"   
		</tns:query>
    </tns:queryCompTyper>
    <tns:queryCompTyper name="DataAccess" >
    	<tns:componentType>DataAccess</tns:componentType>
    	<tns:class>pro.pmmc.genarview.query.GenericQueryCompTyper</tns:class>
    	<tns:args>
    		<tns:arg>t</tns:arg>
    	</tns:args>
    	<tns:query>MATCH (t:Type)&gt;(i:TypeImported), (t:Type)[:USE]&gt;(e:Type)&gt;(ae:Annotation) WITH t AS t, i.fullName AS em, ae.fullName AS ety, COUNT(DISTINCT(e)) AS n WHERE em="javax.persistence.EntityManager" AND ety="javax.persistence.Entity" AND n=1   
		</tns:query>
    </tns:queryCompTyper>
    <tns:queryCompTyper name="Entity" >
    	<tns:componentType>Entity</tns:componentType>
    	<tns:class>pro.pmmc.genarview.query.GenericQueryCompTyper</tns:class>
    	<tns:args>
